services:
  qb-bridge:

    # Build from local Dockerfile
    build:
      context: ../qbd-bridge
      # args:
      #   DB_CLIENT: mariadb  # or "mysql" — installs a DB client inside the container

    # Expose as MySQL Port
    ports:
      - "3306:3306"

    # Mount a directory containing your QBW file
    volumes:
      - ./data:/data

    # Set the file path of your QBW file
    environment:
      - QBW_FILE=/data/my-company-file.qbw
